### ISSUE TITLE
Losing scroll navigation after closing modal with a button

### ISSUE THREAD

**Issue by samuelpietra** [assisrafael/react-bootstrap-utils#10]
With an opened \<Dialog>, if one tries to close it with some button like:
```javascript
footer={({ close }) => (
          <button type="button" onClick={close}>
            Close
          </button>
        )}
```
The \<body class="modal-open"> persists even after this event, therefore disabling scroll navigation

**Comment by assisrafael** [comment]
Fixed by 341dec3
