### ISSUE TITLE
Issue with Table columns

### ISSUE THREAD

**Issue by vbarcellos** [assisrafael/react-bootstrap-utils#12]
Can't pass an object field as attribute for a table column.

My code:
![bugColunas](https://user-images.githubusercontent.com/56827865/80411225-2ed4d100-88a2-11ea-88b0-5255f4c9cc93.png)

Can only work around it using format
![bugColunas2](https://user-images.githubusercontent.com/56827865/80411239-385e3900-88a2-11ea-9d34-961ab9e2c940.png)

**Comment by assisrafael** [comment]
Fixed on ddeff7b
