### ISSUE TITLE
Issue selecting result from autocomplete list

### ISSUE THREAD

**Issue by vbarcellos** [assisrafael/react-bootstrap-utils#19]
![bugAutocomplete](https://user-images.githubusercontent.com/56827865/84291261-3a5f1d00-ab1b-11ea-886e-a58ad86d4a49.gif)

It seems that if you filter something by typing, then select the second option, it assumes that what you selected is the second option rather than the second result of your filtered options.

**Comment by assisrafael** [comment]
Fixed on v0.16.0
