### ISSUE TITLE
Autocomplete doesn't stand external value change

### ISSUE THREAD

**Issue by samuelpietra** [assisrafael/react-bootstrap-utils#21]
After choosing an **Autocomplete** fill suggestion, this field needs to be cleared for new searches. If one uses **setValue** function from parent **useFormControl**, passing an empty string as parameter, **Autocomplete** becomes visually empty, but, when focusing this field again, the last selected suggestion reappears - forcing one to manually erase its content in order to search and get new suggestions

**Comment by assisrafael** [comment]
Fixed on v0.16.0
