### ISSUE TITLE
feat(table): implement table sorting by column

### ISSUE THREAD

**Issue by gabrielpadov** [assisrafael/react-bootstrap-utils#3]
We may sometime need to add sorting a-z or z-a or asc or desc order the attribute numeric of table column.
![tablesort](https://user-images.githubusercontent.com/33489999/77070934-f0f2ac00-69c9-11ea-8e60-7235528e4a8a.png)

**Comment by assisrafael** [comment]
Check the new attribute `columnHeaderFormat` from <Table /> on version 0.8.1.
