### ISSUE TITLE
Issue with FormAutocomplete when there are many options

### ISSUE THREAD

**Issue by vbarcellos** [assisrafael/react-bootstrap-utils#4]
When I filter my options then select one of the filtered values, the value selected wrong. It appears to select relative to the index of all the options. 

Eg: If I type something "cde..." then select the second result out of those, what is actually selected is the second result of all the options, not the one I clicked.

**Comment by assisrafael** [comment]
Fixed on v0.12.0. Please reopen if the problem reappear.
