### ISSUE TITLE
Broken dialogs

### ISSUE THREAD

**Issue by samuelpietra** [assisrafael/react-bootstrap-utils#6]
Dialogs are breaking pages where they're implemented. In some cases, it happens after the triggerElement event, but mostly it doesn't even need any event - simply breaks pages since their opening. The code itselft was literally copied (lines 71-94) from ./demo/DialogExamples.jsx

Generating the following message on Chrome's console:

`Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.`

**Comment by assisrafael** [comment]
Fixed on v0.12.0. Please reopen if the problem reappear.
