### ISSUE TITLE
Issue with dateTime

### ISSUE THREAD

**Issue by vbarcellos** [assisrafael/react-bootstrap-utils#7]
I'm trying to use a FormGroupInput with type="datetime-local". 

When I supply an object as initialValue with the field `dataInicio: "2020-04-13T11:00:00.000Z"` it breaks my application with the message "Uncaught TypeError: value.toISOString is not a function".

**Comment by assisrafael** [comment]
Did you tried v0.14.7? I could not reproduce the error message above.

**Comment by vbarcellos** [comment]
I could not reproduce either. It is either fixed or I made a mistake back then.
